Fix hotfix of prop's name - hopefully travis does now report on the error - fix the hotfix of prop's name - set version to 6.0.0-26

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,7 +9,7 @@ node_js: [
   ]
 script: | # this has to be used, otherwise it executes the tests twice (because of "default build script")
   npm run mocha
-  if [ $? -ne 0 ]; then exit $?; fi # this is added because sometimes it fails and exists with 0 in travis
+  if [ $? -ne 0 ]; then exit 1; fi # this is added because sometimes it fails and exists with 0 in travis
   if [ $TRAVIS_NODE_VERSION == "12" ]; then npm run coverage; fi
 stages:
   - compile
