Cleanup for 6.0.0 - Revert "implement a hack for ObjectID (#363)" - cleanup of various things - re-adding typegoose class with deprecation notice - improved README for 6.0.0 - travis: removed email & api-key for deploy on npm, because not working - package: updating dependencies - package: adding contributors - package: minified "repository"

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,9 +10,8 @@ node_js: [
 # this has to be used, otherwise it executes the tests twice (because of "default build script")
 script: |
   npm run mocha
-  if [[ $TRAVIS_NODE_VERSION == "12" ]]; then
-      npm run coverage
-  fi
+  if [ $? -ne 0 ]; then exit $?; fi # this is added because sometimes it fails and exists with 0 in travis
+  if [ $TRAVIS_NODE_VERSION == "12" ]; then npm run coverage; fi
 stages:
   - compile
   - test
@@ -31,11 +30,10 @@ jobs:
       script: skip
       deploy:
         provider: npm
-        email: benedikt.huss@gmail.com
+        email: $DEPLOY_NPM_EMAIL
         tag: latest
         skip_cleanup: true
-        api_key:
-          secure: pNyluNoFqt4/mH0afzIdGnDHsDqjJTafh766eUIB2jriaEQ0v6DQ/JaTnsx8v7S7W8ibXM4xgoidbAbqs1Y7ZPYTMwlZTIlEa19CUtOdUnP+cT2V4feQMYMi3jlSMoOm7k56CaufFz2yUyGwvqMJFHspXyVbLnpdJWX9OOnL0E42NSBHhs+jBB3QdyLKIiQQzGBHAAsr/Yl2ot3k9ndfyzSPhGkvQWYeRn7AwulWg9LB8qiTFsEXPxtVQOo/tkVbF4pWpA99CZbaY/ibDzm9OYCl73qHMX0N8FG4eB1ByGGUnxGjAJWfvB2QWkZcsnH7ywJCJRjHjaOpkXHmPQVZ0i3F6fGcTg0vyhuQ9W3staYO+kxZa+Ol6EzAZSsUsgWepOJYMfW4w31PKwQsoJrz/efFNORzPfX4GmaRkqXBRfIdYgnrl7SFV3S6ljADPLo3rbAuNYjgZ+Ui7Ged1fHr5OESuEzhue8ldoEcWJGoC78+6UE40XFB0CSnugRt/LVe6JM1fov5LcuwCjtLYTiDR/AsMb8pX6fVlYIbox/zGMVghZlRwc/iSMn6+3RrQGB8f30l1vx+/M/Tb3sHiiTFyXa58uIwGisaQ39//LuwezrYG0sNwzqrV8YEahZxIx9AvqqZ9nGjjp4cKRQ0vt5t58f6Cr/vz1VHhvEtlKMmOA8=
+        api_key: $DEPLOY_NPM_KEY
         on:
           tags: true
     - name: 'Deploy to GitHub Pages'
